name: Build

on:
  pull_request:
    paths-ignore:
     - 'README.md'
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run test
      env:
        CI: true
    - run: node src/cli.js publish --project testbeats --run 'Unit Tests' --slack {SLACK_MVP_URL} --title 'Unit Tests' --ci-info --chart-test-summary --junit 'results/junit.xml'
      if: always()
      env:
        TEST_BEATS_API_KEY: ${{ secrets.TEST_BEATS_API_KEY }}
        SLACK_MVP_URL: ${{ secrets.SLACK_MVP_URL }}